#!/usr/bin/env python
#
# License: BSD
#   https://raw.githubusercontent.com/samiamlabs/dyno/master/LICENCE
#

import rospy
from costmap_converter.msg import ObstacleArrayMsg


class ObstacleRelay:
    def __init__(self):
        rospy.init_node('dynamic_obstacle_relay')

        master_name = rospy.get_param("/rocon/master/name")

        topic_name = '/concert/' + master_name + '/obstacles'
        rospy.Subscriber(topic_name, ObstacleArrayMsg, self.obstacles_callback)

        self.obstacle_pub = rospy.Publisher('/move_base/TebLocalPlannerROS/obstacles',
                              ObstacleArrayMsg, queue_size=10)

    def obstacles_callback(self, obstacles_msg):
        self.obstacle_pub.publish(obstacles_msg)


if __name__ == '__main__':
    try:
        obstacle_relay = ObstacleRelay()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
