#!/usr/bin/env node
/*
  License: BSD
  https://raw.githubusercontent.com/samiamlabs/dyno/master/LICENCE
*/

'use strict';

require('babel-register');
require('babel-polyfill');
require('../src/pouch_main');
