#!/usr/bin/env python
#
# License: BSD
#   https://raw.githubusercontent.com/samiamlabs/dyno/master/LICENCE
#

import rospy
from std_srvs.srv import *

from dyno_world_state.srv import *
from dyno_world_state.msg import *

from visualization_msgs.msg import Marker, MarkerArray
from geometry_msgs.msg import PoseWithCovarianceStamped, PoseStamped, Quaternion, Pose, Point

from collections import namedtuple

from tf.transformations import quaternion_from_euler, euler_from_quaternion

import rospkg
import yaml

LocationTuple = namedtuple("LocationTuple", "pose_stamped, marker, label")


class SimpleWorldState:
    def __init__(self):
        rospy.loginfo("init")

        self.current_pose = PoseStamped()

        self.location_dict = {}

        self.unique_id_counter = 1000

        rospack = rospkg.RosPack()
        self.save_state_filename = rospack.get_path(
            'dyno_world_state') + '/states/save_state.yaml'

        self.init_services()
        self.init_subscribers()
        self.init_publishers()

        self.handle_load_state(None)

    def init_services(self):
        self.add_current_pose_service = rospy.Service(
            '/world_state/add_current_location', AddCurrentLocation, self.handle_add_current_pose)

        self.add_current_pose_service = rospy.Service(
            '/world_state/clear_locations', Empty, self.handle_clear_poses)

        self.save_state_service = rospy.Service(
            '/world_state/save', Empty, self.handle_save_state)

        self.load_state_service = rospy.Service(
            '/world_state/load', Empty, self.handle_load_state)

    def handle_add_current_pose(self, request):
        rospy.loginfo("Adding current pose as %s:", request.name)
        rospy.loginfo(self.current_pose)

        location_name = request.name

        marker = self.create_location_marker(self.current_pose)
        label = self.create_location_label(self.current_pose, location_name)

        location = LocationTuple(
            pose_stamped=self.current_pose, marker=marker, label=label)
        self.location_dict[str(location_name)] = location

        rospy.loginfo("Number of poses: %d", len(self.location_dict))

        response = AddCurrentLocationResponse()
        response.success = True

        return response

    def handle_clear_poses(self, request):
        rospy.loginfo("Clearing poses!")
        self.location_dict = {}

        rospy.loginfo("Number of poses: %d", len(self.location_dict))
        return EmptyResponse()

    def handle_save_state(self, request):
        with open(self.save_state_filename, 'w') as outfile:
            yaml.dump(self.location_dict, outfile, default_flow_style=False)

        return EmptyResponse()

    def handle_load_state(self, request):

        try:
            with open(self.save_state_filename, 'r') as infile:
                try:
                    self.location_dict = yaml.load(infile)
                except yaml.YAMLError as exc:
                    rospy.logerr('Failed to load state!')
        except:
            rospy.logwarn("No save file found!")

        return EmptyResponse()

    def init_subscribers(self):
        rospy.Subscriber("/robot_pose", PoseStamped,
                         self.current_pose_callback)

    def init_publishers(self):
        self.location_pub = rospy.Publisher(
            '/world_state/locations', LocationArray, queue_size=1)

        self.marker_pub = rospy.Publisher(
            '/world_state/markers', MarkerArray, queue_size=1)

    def current_pose_callback(self, pose_msg):
        self.current_pose = pose_msg

    def create_location_marker(self, location):
        marker_scale = .33
        marker_lifetime = 1  # 0 if forever
        marker_ns = 'location'
        marker_color = {'r': 0.4, 'g': 0.4, 'b': 0.7, 'a': 0.9}

        marker = Marker()

        marker.ns = marker_ns
        marker.type = Marker.CYLINDER

        # Generate unique id
        marker.id = self.unique_id_counter
        self.unique_id_counter += 1

        marker.action = Marker.ADD
        marker.lifetime = rospy.Duration(marker_lifetime)

        marker.scale.x = marker_scale
        marker.scale.y = marker_scale
        marker.scale.z = 0.01

        marker.color.r = marker_color['r']
        marker.color.g = marker_color['g']
        marker.color.b = marker_color['b']
        marker.color.a = marker_color['a']

        marker.header.frame_id = location.header.frame_id
        marker.header.stamp = rospy.Time.now()

        rospy.loginfo(location.header.frame_id)

        marker.pose = location.pose

        return marker

    def create_location_label(self, location, text):
        font_size = 0.24
        marker_lifetime = 1  # 0 if forever
        marker_ns = 'location_labels'
        marker_color = {'r': 0.5, 'g': 0.2, 'b': 0.2, 'a': 1.0}

        label_marker = Marker()

        label_marker.ns = marker_ns

        # Generate unique id
        label_marker.id = self.unique_id_counter
        self.unique_id_counter += 1

        label_marker.type = Marker.TEXT_VIEW_FACING
        label_marker.action = Marker.ADD
        label_marker.lifetime = rospy.Duration(marker_lifetime)

        label_marker.scale.z = font_size
        label_marker.text = text

        label_marker.color.r = marker_color['r']
        label_marker.color.g = marker_color['g']
        label_marker.color.b = marker_color['b']
        label_marker.color.a = marker_color['a']

        label_marker.header.frame_id = location.header.frame_id
        label_marker.header.stamp = rospy.Time.now()

        label_marker.pose = self.modify_location_label_pose(location.pose)

        return label_marker

    def modify_location_label_pose(self, pose):
        temp_pose = pose

        q = temp_pose.orientation
        angles = euler_from_quaternion([q.x, q.y, q.z, q.w])
        alpha = angles[2]

        modified_x = temp_pose.position.x
        modified_y = temp_pose.position.y
        modified_z = temp_pose.position.z + 0.15

        q_angle = quaternion_from_euler(0, 0, alpha, axes='sxyz')
        q = Quaternion(*q_angle)

        temp_pose = Pose(Point(modified_x, modified_y, modified_z), q)

        return temp_pose

    def update(self):
        pass

    def publish(self):
        location_array_msg = LocationArray()

        for key in self.location_dict:
            location_msg = Location()
            location_msg.name = key
            location_msg.pose = self.location_dict[key].pose_stamped.pose
            location_array_msg.locations.append(location_msg)

        self.location_pub.publish(location_array_msg)

        marker_array_msg = MarkerArray()

        for key in self.location_dict:
            marker_array_msg.markers.append(self.location_dict[key].marker)
            marker_array_msg.markers.append(self.location_dict[key].label)

        self.marker_pub.publish(marker_array_msg)


if __name__ == '__main__':
    rospy.init_node('simple_world_state')

    simple_world_state = SimpleWorldState()

    rate = rospy.Rate(2)
    while not rospy.is_shutdown():
        simple_world_state.update()
        simple_world_state.publish()
        rate.sleep()
