#!/usr/bin/env python

import rospy
from sensor_msgs.msg import LaserScan

pub = rospy.Publisher('/scan', LaserScan, queue_size=10)


def callback(msg):
    msg.header.stamp = rospy.Time.now()
    pub.publish(msg)


def scan_time_fixer():
    rospy.init_node('scan_time_fixer')
    rospy.Subscriber("/unity_scan", LaserScan, callback)
    rospy.spin()

if __name__ == '__main__':
    try:
        scan_time_fixer()
    except rospy.ROSInterruptException:
        pass
