#!/usr/bin/env python
#
# License: BSD
#   https://raw.githubusercontent.com/samiamlabs/dyno/master/LICENCE
#

import sys
import rospy
import rospkg
from cartographer_ros_msgs.srv import *
from std_srvs.srv import *


def save_state_server():
    save_state_service = rospy.Service('/save_cartographer_state', Empty, handle_save_state)


def handle_save_state(req):
    rospack = rospkg.RosPack()

    save_state_filename = rospack.get_path('dyno_localization') + '/states/save_state.pbstream'
    rospy.loginfo(save_state_filename)

    write_state_client(save_state_filename)

    return EmptyResponse()


def write_state_client(filename):
    rospy.wait_for_service('/write_state')
    try:
        write_state = rospy.ServiceProxy('/write_state', WriteState)
        write_state(filename)
    except rospy.ServiceException, e:
        print "Service call failed: %s"%e

if __name__ == "__main__":
    rospy.init_node('save_cartographer_state')

    save_state_server()

    rospy.spin()
